// src/data/requestsData.js

// This array contains the static request data
export const requests = [
  {
    id: 1,
    department: 'Логістика',
    executor: 'Іван Петренко',
    vehicle: 'DAF XF 105',
    timeBegin: '10:00',
    timeEnd: '11:00',
    weight: '22т',
    route: 'Київ - Житомир - Рівне - Львів',
    status: 'погрузка',
  },
  {
    id: 2,
    department: 'Склад',
    executor: 'Марія Коваленко',
    vehicle: 'Mercedes Actros',
    timeBegin: '11:30',
    timeEnd: '12:30',
    weight: '18т',
    route: 'Харків - Полтава - Кременчук - Одеса',
    status: 'перевезення',
  },
  {
    id: 3,
    department: 'Експорт',
    executor: 'Олег Сидоренко',
    vehicle: 'Volvo FH',
    timeBegin: '09:15',
    timeEnd: '12:15',
    weight: '24т',
    route: 'Дніпро - Запоріжжя - Миколаїв - Варшава',
    status: 'сформована',
  },
  {
    id: 4,
    department: 'Логістика',
    executor: 'Андрій Ковальчук',
    vehicle: 'Scania R450',
    timeBegin: '08:00',
    timeEnd: '16:00',
    weight: '20т',
    route: 'Одеса - Умань - Вінниця - Хмельницький',
    status: 'перевезення',
  },
  {
    id: 5,
    department: 'Склад',
    executor: 'Тетяна Мельник',
    vehicle: 'MAN TGX',
    timeBegin: '07:30',
    timeEnd: '15:30',
    weight: '19т',
    route: 'Львів - Тернопіль - Хмельницький - Київ',
    status: 'погрузка',
  },
  {
    id: 6,
    department: 'Експорт',
    executor: 'Василь Шевченко',
    vehicle: 'Renault T520',
    timeBegin: '06:45',
    timeEnd: '18:45',
    weight: '23т',
    route: 'Київ - Луцьк - Ковель - Люблін',
    status: 'сформована',
  },
  {
    id: 7,
    department: 'Логістика',
    executor: 'Ірина Коваль',
    vehicle: 'DAF CF',
    timeBegin: '09:30',
    timeEnd: '17:30',
    weight: '21т',
    route: 'Харків - Суми - Чернігів - Київ',
    status: 'розгруска',
  },
  {
    id: 8,
    department: 'Склад',
    executor: 'Сергій Мороз',
    vehicle: 'Mercedes Actros',
    timeBegin: '10:15',
    timeEnd: '19:15',
    weight: '17т',
    route: 'Одеса - Миколаїв - Херсон - Мелітополь',
    status: 'перевезення',
  },
  {
    id: 9,
    department: 'Експорт',
    executor: 'Наталія Павленко',
    vehicle: 'Volvo FH16',
    timeBegin: '07:00',
    timeEnd: '16:00',
    weight: '25т',
    route: 'Львів - Івано-Франківськ - Чернівці - Бухарест',
    status: 'сформована',
  },
  {
    id: 10,
    department: 'Логістика',
    executor: 'Максим Литвин',
    vehicle: 'Scania S730',
    timeBegin: '08:45',
    timeEnd: '17:45',
    weight: '22т',
    route: 'Дніпро - Кривий Ріг - Кропивницький - Умань',
    status: 'погрузка',
  },
  {
    id: 11,
    department: 'Склад',
    executor: 'Олена Білик',
    vehicle: 'MAN TGS',
    timeBegin: '11:00',
    timeEnd: '20:00',
    weight: '18т',
    route: 'Київ - Біла Церква - Вінниця - Хмельницький',
    status: 'перевезення',
  },
  {
    id: 12,
    department: 'Експорт',
    executor: 'Роман Дубовий',
    vehicle: 'Renault T480',
    timeBegin: '06:30',
    timeEnd: '15:30',
    weight: '24т',
    route: 'Харків - Дніпро - Запоріжжя - Маріуполь',
    status: 'сформована',
  },
  {
    id: 13,
    department: 'Логістика',
    executor: 'Юлія Савченко',
    vehicle: 'DAF XF',
    timeBegin: '09:00',
    timeEnd: '18:00',
    weight: '20т',
    route: 'Львів - Луцьк - Рівне - Житомир',
    status: 'розгруска',
  },
  {
    id: 14,
    department: 'Склад',
    executor: 'Віктор Козак',
    vehicle: 'Mercedes Arocs',
    timeBegin: '10:30',
    timeEnd: '19:30',
    weight: '19т',
    route: 'Одеса - Вознесенськ - Первомайськ - Умань',
    status: 'перевезення',
  },
  {
    id: 15,
    department: 'Експорт',
    executor: 'Людмила Ткач',
    vehicle: 'Volvo FM',
    timeBegin: '07:15',
    timeEnd: '16:15',
    weight: '23т',
    route: 'Київ - Полтава - Харків - Суми',
    status: 'сформована',
  },
  {
    id: 16,
    department: 'Логістика',
    executor: 'Павло Гончар',
    vehicle: 'Scania G410',
    timeBegin: '08:30',
    timeEnd: '17:30',
    weight: '21т',
    route: 'Дніпро - Павлоград - Покровськ - Краматорськ',
    status: 'погрузка',
  },
  {
    id: 17,
    department: 'Склад',
    executor: 'Оксана Лисенко',
    vehicle: 'MAN TGA',
    timeBegin: '11:15',
    timeEnd: '20:15',
    weight: '17т',
    route: 'Львів - Стрий - Івано-Франківськ - Чернівці',
    status: 'перевезення',
  },
  {
    id: 18,
    department: 'Експорт',
    executor: 'Денис Кравчук',
    vehicle: 'Renault K520',
    timeBegin: '06:00',
    timeEnd: '15:00',
    weight: '25т',
    route: 'Харків - Полтава - Київ - Житомир',
    status: 'сформована',
  },
  {
    id: 19,
    department: 'Логістика',
    executor: 'Галина Шевчук',
    vehicle: 'DAF CF',
    timeBegin: '09:45',
    timeEnd: '18:45',
    weight: '22т',
    route: 'Одеса - Южне - Миколаїв - Херсон',
    status: 'розгруска',
  },
  {
    id: 20,
    department: 'Склад',
    executor: 'Микола Бондар',
    vehicle: 'Mercedes Atego',
    timeBegin: '10:45',
    timeEnd: '19:45',
    weight: '18т',
    route: 'Київ - Бровари - Чернігів - Суми',
    status: 'перевезення',
  },
  {
    id: 21,
    department: 'Експорт',
    executor: 'Софія Марченко',
    vehicle: 'Volvo FMX',
    timeBegin: '07:45',
    timeEnd: '16:45',
    weight: '24т',
    route: 'Львів - Рава-Руська - Люблін - Варшава',
    status: 'сформована',
  },
  {
    id: 22,
    department: 'Логістика',
    executor: 'Артем Василенко',
    vehicle: 'Scania P410',
    timeBegin: '08:15',
    timeEnd: '17:15',
    weight: '20т',
    route: 'Дніпро - Запоріжжя - Мелітополь - Бердянськ',
    status: 'погрузка',
  },
  {
    id: 23,
    department: 'Склад',
    executor: 'Лариса Ткаченко',
    vehicle: 'MAN TGX',
    timeBegin: '11:45',
    timeEnd: '20:45',
    weight: '19т',
    route: 'Харків - Ізюм - Словʼянськ - Краматорськ',
    status: 'перевезення',
  },
  {
    id: 24,
    department: 'Експорт',
    executor: 'Богдан Кузьменко',
    vehicle: 'Renault D',
    timeBegin: '06:15',
    timeEnd: '15:15',
    weight: '23т',
    route: 'Одеса - Кишинів - Ясси - Бухарест',
    status: 'сформована',
  },
  {
    id: 25,
    department: 'Логістика',
    executor: 'Марина Попова',
    vehicle: 'DAF LF',
    timeBegin: '09:15',
    timeEnd: '18:15',
    weight: '21т',
    route: 'Київ - Вінниця - Хмельницький - Тернопіль',
    status: 'розгруска',
  },
  {
    id: 26,
    department: 'Склад',
    executor: 'Ігор Семенов',
    vehicle: 'Mercedes Antos',
    timeBegin: '10:00',
    timeEnd: '19:00',
    weight: '17т',
    route: 'Львів - Ужгород - Кошице - Братислава',
    status: 'перевезення',
  },
  {
    id: 27,
    department: 'Експорт',
    executor: 'Катерина Романенко',
    vehicle: 'Volvo FL',
    timeBegin: '07:30',
    timeEnd: '16:30',
    weight: '25т',
    route: 'Харків - Дніпро - Кривий Ріг - Миколаїв',
    status: 'сформована',
  },
  {
    id: 28,
    department: 'Логістика',
    executor: 'Станіслав Мельников',
    vehicle: 'Scania L320',
    timeBegin: '08:00',
    timeEnd: '17:00',
    weight: '22т',
    route: 'Одеса - Ізмаїл - Рені - Галац',
    status: 'погрузка',
  },
  {
    id: 29,
    department: 'Склад',
    executor: 'Валентина Петрова',
    vehicle: 'MAN eTGM',
    timeBegin: '11:30',
    timeEnd: '20:30',
    weight: '18т',
    route: 'Київ - Фастів - Біла Церква - Умань',
    status: 'перевезення',
  },
  {
    id: 30,
    department: 'Експорт',
    executor: 'Олександр Іванченко',
    vehicle: 'Renault C',
    timeBegin: '06:45',
    timeEnd: '15:45',
    weight: '24т',
    route: 'Львів - Мукачево - Будапешт - Відень',
    status: 'сформована',
  },
  {
    id: 31,
    department: 'Логістика',
    executor: 'Вікторія Захарченко',
    vehicle: 'DAF CF Electric',
    timeBegin: '09:30',
    timeEnd: '18:30',
    weight: '20т',
    route: 'Дніпро - Нікополь - Енергодар - Мелітополь',
    status: 'розгруска',
  },
  {
    id: 32,
    department: 'Склад',
    executor: 'Руслан Григоренко',
    vehicle: 'Mercedes eActros',
    timeBegin: '10:15',
    timeEnd: '19:15',
    weight: '19т',
    route: 'Харків - Лозова - Павлоград - Дніпро',
    status: 'перевезення',
  },
  {
    id: 33,
    department: 'Експорт',
    executor: 'Анастасія Федорова',
    vehicle: 'Volvo VNR Electric',
    timeBegin: '07:00',
    timeEnd: '16:00',
    weight: '23т',
    route: 'Київ - Чернігів - Гомель - Мінськ',
    status: 'сформована',
  },
];
